# this config was migrated from renv.lock on 2025-12-20
[project]
name = "Data Science for business"
r_version = "4.5"

repositories = [
  { alias = "CRAN", url = "https://packagemanager.posit.co/cran/latest" },
]

dependencies = [
  { name = "DBI", repository = "CRAN" },
  { name = "PerformanceAnalytics", repository = "CRAN" },
  { name = "R6", repository = "CRAN" },
  { name = "RColorBrewer", repository = "CRAN" },
  { name = "RcppRoll", repository = "CRAN" },
  { name = "RobStatTM", repository = "CRAN" },
  { name = "SQUAREM", repository = "CRAN" },
  { name = "TTR", repository = "CRAN" },
  { name = "askpass", repository = "CRAN" },
  { name = "backports", repository = "CRAN" },
  { name = "base64enc", repository = "CRAN" },
  { name = "bit", repository = "CRAN" },
  { name = "bit64", repository = "CRAN" },
  { name = "blob", repository = "CRAN" },
  { name = "bslib", repository = "CRAN" },
  { name = "cachem", repository = "CRAN" },
  { name = "callr", repository = "CRAN" },
  { name = "cellranger", repository = "CRAN" },
  { name = "cli", repository = "CRAN" },
  { name = "clipr", repository = "CRAN" },
  { name = "clock", repository = "CRAN" },
  { name = "conflicted", repository = "CRAN" },
  { name = "cpp11", repository = "CRAN" },
  { name = "crayon", repository = "CRAN" },
  { name = "diagram", repository = "CRAN" },
  { name = "dplyr", repository = "CRAN" },
  { name = "farver", repository = "CRAN" },
  { name = "fastmap", repository = "CRAN" },
  { name = "fontawesome", repository = "CRAN" },
  { name = "forecast", repository = "CRAN" },
  { name = "fracdiff", repository = "CRAN" },
  { name = "fs", repository = "CRAN" },
  { name = "furrr", repository = "CRAN" },
  { name = "generics", repository = "CRAN" },
  { name = "ggrepel", repository = "CRAN" },
  { name = "globals", repository = "CRAN" },
  { name = "glue", repository = "CRAN" },
  { name = "gower", repository = "CRAN" },
  { name = "gtable", repository = "CRAN" },
  { name = "haven", repository = "CRAN" },
  { name = "highr", repository = "CRAN" },
  { name = "htmlwidgets", repository = "CRAN" },
  { name = "httr", repository = "CRAN" },
  { name = "ids", repository = "CRAN" },
  { name = "ipred", repository = "CRAN" },
  { name = "janitor", repository = "CRAN" },
  { name = "jquerylib", repository = "CRAN" },
  { name = "jsonlite", repository = "CRAN" },
  { name = "knitr", repository = "CRAN" },
  { name = "labeling", repository = "CRAN" },
  { name = "lazyeval", repository = "CRAN" },
  { name = "lifecycle", repository = "CRAN" },
  { name = "lmtest", repository = "CRAN" },
  { name = "lubridate", repository = "CRAN" },
  { name = "memoise", repository = "CRAN" },
  { name = "mime", repository = "CRAN" },
  { name = "modelr", repository = "CRAN" },
  { name = "mvtnorm", repository = "CRAN" },
  { name = "numDeriv", repository = "CRAN" },
  { name = "padr", repository = "CRAN" },
  { name = "pcaPP", repository = "CRAN" },
  { name = "pkgconfig", repository = "CRAN" },
  { name = "plogr", repository = "CRAN" },
  { name = "prettyunits", repository = "CRAN" },
  { name = "processx", repository = "CRAN" },
  { name = "prodlim", repository = "CRAN" },
  { name = "progress", repository = "CRAN" },
  { name = "ps", repository = "CRAN" },
  { name = "quadprog", repository = "CRAN" },
  { name = "rappdirs", repository = "CRAN" },
  { name = "readxl", repository = "CRAN" },
  { name = "recipes", repository = "CRAN" },
  { name = "rematch", repository = "CRAN" },
  { name = "rematch2", repository = "CRAN" },
  { name = "renv", repository = "CRAN" },
  { name = "repr", repository = "CRAN" },
  { name = "reprex", repository = "CRAN" },
  { name = "rlang", repository = "CRAN" },
  { name = "rrcov", repository = "CRAN" },
  { name = "rstudioapi", repository = "CRAN" },
  { name = "sass", repository = "CRAN" },
  { name = "scales", repository = "CRAN" },
  { name = "shape", repository = "CRAN" },
  { name = "snakecase", repository = "CRAN" },
  { name = "stringi", repository = "CRAN" },
  { name = "sys", repository = "CRAN" },
  { name = "tidyquant", repository = "CRAN" },
  { name = "tidyselect", repository = "CRAN" },
  { name = "tidyverse", repository = "CRAN" },
  { name = "timechange", repository = "CRAN" },
  { name = "tseries", repository = "CRAN" },
  { name = "tsfeatures", repository = "CRAN" },
  { name = "tzdb", repository = "CRAN" },
  { name = "urca", repository = "CRAN" },
  { name = "uuid", repository = "CRAN" },
  { name = "vctrs", repository = "CRAN" },
  { name = "viridisLite", repository = "CRAN" },
  { name = "withr", repository = "CRAN" },
  { name = "writexl", repository = "CRAN" },
  { name = "xts", repository = "CRAN" },
  "S7",
    "logger",
    "umap",
]
